#!/bin/bash
set -euo pipefail

[ $# -ne 1 ] && echo "Usage: $0 <scala version>" && exit 1

cd "$(dirname "$0")/.."
sbt -DCI=1 "++$1" dom/scalafix

cd "$(dirname "$0")"
series="${1%.*}"
file="${series/./_}.txt"
echo -n "Validating $file ... "

help='Run `sbt prePR` and check in the differences to the '"$(basename "$0") directory"

if [ ! -e "$file" ]; then
  echo "file not found. $help"
  exit 2
elif [ -n "$(git status --porcelain -- "$file")" ]; then
  echo "out-of-date. $help"
  exit 3
else
  echo "ok"
fi
